services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.58.2-noble
    container_name: playwright
    working_dir: /workspace
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
      - .pnpm-store:/pnpm-store
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      NODE_ENV: test
      WP_ENVIRONMENT: local
      WP_E2E_SKIP_ENV_SETUP: "true"

    command: >
      sh -c "
        npm i -g pnpm
        pnpm install --frozen-lockfile --yes
        tail -f /dev/null
      "

volumes:
  node_modules:
