packages:
  - 'themes/*'
  - 'plugins/*'
  - 'packages/*'
  - 'tools/*'
catalog:
  '@bcgov/bc-sans': ^2.1.0
  '@bcgov/design-tokens': ^4.0.0
  '@fortawesome/fontawesome-free': 7.2.0
  '@nx/devkit': 22.5.4
  '@nx/plugin': ^22.6.2
  '@playwright/test': 1.58.2
  '@swc-node/register': ~1.11.1
  '@swc/cli': ~0.8.0
  '@swc/core': ~1.15.21
  '@swc/helpers': ~0.5.20
  '@types/jest': ^30.0.0
  '@types/node': 20.19.9
  '@wordpress/block-editor': wp-6.7
  '@wordpress/blocks': wp-6.7
  '@wordpress/components': wp-6.7
  '@wordpress/core-data': wp-6.7
  '@wordpress/data': wp-6.7
  '@wordpress/e2e-test-utils-playwright': wp-6.7
  '@wordpress/element': wp-6.7
  '@wordpress/env': wp-6.7
  '@wordpress/i18n': wp-6.7
  '@wordpress/scripts': ^31.7.0
  '@wordpress/stylelint-config': wp-6.7
  'chokidar-cli': ^3.0.0
  'concurrently': ^9.2.1
  'eslint-plugin-playwright': ^2.10.1
  'eslint-plugin-prefer-arrow': ^1.2.3
  'js-beautify': ^1.15.4
  'nx': ^23.0.0
  'prettier': ~3.6.2
  'react': 18.3.1
  'tslib': ^2.8.1
  'typescript': ~5.3.0
  'vitepress': 2.0.0-alpha.17
minimumReleaseAge: 1440
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  'core-js': false
  'core-js-pure': false
  'esbuild': false
  'fs-ext': false
  'fs-ext-extra-prebuilt': false
  'nx': false
  'unrs-resolver': false
overrides:
  markdownlint-cli: 0.49.0
