packages:
  - 'themes/*'
  - 'plugins/*'
  - 'packages/*'
  - 'tools/*'
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  core-js: false
  core-js-pure: false
  esbuild: false
  fs-ext: false
  fs-ext-extra-prebuilt: false
  nx: false
  unrs-resolver: false
