name: Release Subproject and Update packages.json
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Project to release'
        required: true
        type: choice
        options:
          - bcew-blocks
          - bcew-belleville-terminal
          - bcew-theme-2
          - design-system-wordpress-child-theme-ticorp
      version:
        description: 'Version to release (for example: 1.2.3)'
        required: true
        type: string
      is_prerelease:
        description: 'Is this a pre-release?'
        type: boolean

concurrency:
  group: composer-repo-update
  cancel-in-progress: false

jobs:
  build-and-deploy:
    permissions:
       contents: write
       pages: write
       id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9
        with:
            version: 10
            cache: true

      - name: Setup Node.js 24
        uses: actions/setup-node@v6.4.0
        with:
            node-version: 24
            cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Parse Inputs
        id: vars
        shell: bash
        run: |
          echo "name=${{ inputs.name }}" >> $GITHUB_OUTPUT
          echo "version_normalized=${{ inputs.version }}" >> $GITHUB_OUTPUT
          echo "version=v${{ inputs.version }}" >> $GITHUB_OUTPUT
          echo "project_path=$(npx nx show project ${{ inputs.name }} --json | jq -r .root)" >> $GITHUB_OUTPUT
          echo "is_prerelease=${{ inputs.is_prerelease }}" >> $GITHUB_OUTPUT
          echo "tag=${{ inputs.name }}/v${{ inputs.version }}" >> $GITHUB_OUTPUT

      - name: Install Composer dependencies
        run: npx nx run ${{ steps.vars.outputs.name }}:composer-install

      - name: Nx Build
        run: npx nx run ${{ steps.vars.outputs.name }}:build

      - name: Update versions and zip build artifacts
        run: |
            bash .github/scripts/prepare-release-zip.sh \
              "${{ steps.vars.outputs.project_path }}" \
              "${{ steps.vars.outputs.name }}" \
              "${{ steps.vars.outputs.version_normalized }}"

      - name: Create tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.vars.outputs.tag }}
        run: |
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists"
          else
            git tag "$TAG"
            git push origin "$TAG"
          fi

      - name: Generate changelog
        id: build_changelog
        if: ${{ inputs.tag_name != '' }}
        uses: mikepenz/release-changelog-builder-action@v6.2.2
        with:
            includeOnlyPaths: ${{ steps.vars.outputs.project_path }}
            ignorePreReleases: "false"
            # Todo: Automatically detect previous tag, rather than hardcoding.
            # This is the initial commit of the repository, so all PRs will be included in the changelog until we can set the fromTag dynamically.
            fromTag: "d6725a2e0088842eaf5636847efc3a77d60564a5"
            toTag: ${{ steps.vars.outputs.tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ steps.vars.outputs.project_path }}/dist.zip
          tag_name: ${{ steps.vars.outputs.tag }}
          prerelease: ${{ steps.vars.outputs.is_prerelease }}
          body: ${{steps.build_changelog.outputs.changelog}}

      - name: Update packages.json
        env:
          REPOSITORY: ${{ github.repository }}
          TAG: ${{ steps.vars.outputs.tag }}
          VERSION: ${{ steps.vars.outputs.version }}
          PROJECT_PATH: ${{ steps.vars.outputs.project_path }}
        run: |
          curl -sL https://${{ github.repository_owner }}.github.io/bcew-monorepo/packages.json -o packages.json || echo '{"packages":{}}' > packages.json

          mkdir public

          php .github/scripts/update-packages.php

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
